/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-07 02:18:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ACTIVITY;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1664934107135L));
    _jspx_dependants.put("jar:file:/C:/Users/JS/Desktop/project_1/Group4-Merge/golfzonTech_semi_project1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>액티비티 등록</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/footer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/activity/insert.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- headarea -->\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("	    <div id=\"header_up\">\r\n");
      out.write("	      <div id=\"logo\">\r\n");
      out.write("	        <a href=\"home.do\">\r\n");
      out.write("	          <img id=\"logo_img\" src=\"CSS/logo/logo_small.png\" alt=\"logo_img\">\r\n");
      out.write("	        </a>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div id=\"account\">\r\n");
      out.write("	        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div id=\"header_nav\">\r\n");
      out.write("	      <ul id=\"nav_box\">\r\n");
      out.write("	        <li class=\"nav_item\">\r\n");
      out.write("	          <a href=\"club_selectAll.do\">모임</a>\r\n");
      out.write("	        </li>\r\n");
      out.write("	        <li class=\"nav_item\">\r\n");
      out.write("	          <a href=\"activity_selectAll.do\">액티비티</a>\r\n");
      out.write("	        </li>\r\n");
      out.write("	        <li class=\"nav_item\">\r\n");
      out.write("	          <a href=\"event_selectAll.do\">이벤트</a>\r\n");
      out.write("	        </li>\r\n");
      out.write("	      </ul>\r\n");
      out.write("	    </div>\r\n");
      out.write("  	</div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("        <!-- 액티비티(타이틀) -->\r\n");
      out.write("        <div id=\"activity_name_box\">\r\n");
      out.write("            <div id=\"insert_title\">\r\n");
      out.write("                <p style=\"font-size: 30px; padding-left: 30px;\">\r\n");
      out.write("                    <strong style=\"color: rgb(24, 64, 173);\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\r\n");
      out.write("                    님의 액티비티 개설\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- 액티비티 버튼영역 -->\r\n");
      out.write("        <div id=\"activity_content\">\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"activity_selectAll.do\">목록</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <!-- insert 영역-->\r\n");
      out.write("        <form action=\"activity_insertOK.do\" method=\"post\" enctype=\"multipart/form-data\" name=\"submit_info\" onsubmit=\"return checkValue()\">\r\n");
      out.write("            <input hidden name=\"club_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("            <div id=\"activity_content_box\">\r\n");
      out.write("                <div id=\"access_power\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <select name=\"club_id\" id=\"club_id\" name=\"club_id\">\r\n");
      out.write("                                <option value=\"0\" selected>전체공개</option>\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                            <input type=\"text\" id=\"act_name\" name=\"act_name\" maxlength=\"25\">\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <input type=\"submit\" id=\"act_insert_submit\" value=\"개 설\">\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div id=\"flex\">\r\n");
      out.write("                    <div id=\"activity_main_left\">\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li style=\"font-weight: bold; font-size: 20px;\">[ 액티비티 대표사진 ]</li>\r\n");
      out.write("                            <li><img src=\"CSS/icon/activity.png\" alt=\"\" id=\"preview_image\"></li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <input type=\"file\" id=\"fname\" name=\"fname\">\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li style=\"font-weight: bold; font-size: 20px;\">[ 액티비티 소개 ]</li>\r\n");
      out.write("                            <li><textarea id=\"act_content\" name=\"act_content\" maxlength=\"250\"></textarea></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div id=\"activity_main_right\">\r\n");
      out.write("                        <div id=\"activity_info\">\r\n");
      out.write("                            <p style=\"font-weight: bold; font-size: 20px; margin-bottom: 20px;\">[ 액티비티 정보 ]</p>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>[ 기간 ]</li>\r\n");
      out.write("                                <li class=\"right_list_top\">\r\n");
      out.write("                                    라운딩날짜 : <input type=\"datetime-local\" id=\"rdate\" name=\"rdate\" value=\"\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"right_list_top\" style=\"margin-bottom: 50px;\">\r\n");
      out.write("                                    모집마감일 : <input type=\"datetime-local\" id=\"adate\" name=\"adate\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    [ 조건 ]\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"right_list_bottom\">\r\n");
      out.write("                                    지 역 : \r\n");
      out.write("                                    <select name=\"location\" id=\"location\" name=\"location\" style=\"width: 80px;\" onchange=\"location_cc(this)\">\r\n");
      out.write("                                        <option selected hidden>지역</option>\r\n");
      out.write("					                    <option value=\"서울\">서울</option>\r\n");
      out.write("					                    <option value=\"경기\">경기</option>\r\n");
      out.write("					                    <option value=\"강원\">강원</option>\r\n");
      out.write("					                    <option value=\"전북\">전북</option>\r\n");
      out.write("					                    <option value=\"전남\">전남</option>\r\n");
      out.write("					                    <option value=\"경북\">경북</option>\r\n");
      out.write("					                    <option value=\"경남\">경남</option>\r\n");
      out.write("					                    <option value=\"충북\">충북</option>\r\n");
      out.write("					                    <option value=\"충남\">충남</option>\r\n");
      out.write("					                    <option value=\"제주\">제주</option>\r\n");
      out.write("					                    <option value=\"대전\">대전</option>\r\n");
      out.write("					                    <option value=\"인천\">인천</option>\r\n");
      out.write("					                    <option value=\"광주\">광주</option>\r\n");
      out.write("					                    <option value=\"대구\">대구</option>\r\n");
      out.write("					                    <option value=\"부산\">부산</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"right_list_bottom\">\r\n");
      out.write("                                    CC명 :\r\n");
      out.write("                                    <select name=\"cc_id\" id=\"cc_id\" name=\"cc_id\" style=\"width: 200px;\">\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"right_list_bottom\">\r\n");
      out.write("                                    성 별 :\r\n");
      out.write("                                    <select name=\"gender\" id=\"gender\" name=\"gender\" style=\"width: 80px;\">\r\n");
      out.write("                                        <option value=\"무관\">무관</option>\r\n");
      out.write("                                        <option value=\"남\">남</option>\r\n");
      out.write("                                        <option value=\"여\">여</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"right_list_bottom\">\r\n");
      out.write("                                    연령대 :\r\n");
      out.write("                                    <select name=\"age\" id=\"age\" name=\"age\", value=0 style=\"width: 100px;\">\r\n");
      out.write("                                        <option value=0>무관</option>\r\n");
      out.write("                                        <option value=\"10\">10대</option>\r\n");
      out.write("                                        <option value=\"20\">20대</option>\r\n");
      out.write("                                        <option value=\"30\">30대</option>\r\n");
      out.write("                                        <option value=\"40\">40대</option>\r\n");
      out.write("                                        <option value=\"50\">50대</option>\r\n");
      out.write("                                        <option value=\"60\">60대 이상</option>\r\n");
      out.write("                                    </select>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li class=\"right_list_bottom\">\r\n");
      out.write("                                    비용(만원) :\r\n");
      out.write("                                    <input type=\"number\" id=\"cost\" name=\"cost\" value=\"10\" style=\"width: 80px;\">\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("    	// 기간 value 및 최소날짜 지정\r\n");
      out.write("        let today = new Date().toISOString();\r\n");
      out.write("        today = today.slice(0,-8);\r\n");
      out.write("        document.getElementById('rdate').setAttribute('value',today);\r\n");
      out.write("        document.getElementById('rdate').setAttribute('min',today);\r\n");
      out.write("        document.getElementById('adate').setAttribute('value',today);\r\n");
      out.write("        document.getElementById('adate').setAttribute('min',today);\r\n");
      out.write("\r\n");
      out.write("        let adate = \"2022-10-02T05:32\"\r\n");
      out.write("        console.log(today);\r\n");
      out.write("        console.log(adate);\r\n");
      out.write("        console.log(adate > today);\r\n");
      out.write("        console.log(adate < today);\r\n");
      out.write("\r\n");
      out.write("        // 개설 전 조건 확인\r\n");
      out.write("        function checkValue() {\r\n");
      out.write("            var form = document.submit_info;\r\n");
      out.write("\r\n");
      out.write("            if(!form.act_name.value) {\r\n");
      out.write("                alert(\"액티비티 제목를 작성해주세요.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            if(!form.act_content.value) {\r\n");
      out.write("                alert(\"액티비티 소개를 작성해주세요.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("            if(form.rdate.value <= form.adate.value) {\r\n");
      out.write("                alert(\"모집마감일을 라운딩날짜보다 이전으로 설정해주세요.\");\r\n");
      out.write("                return false;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        // 이미지 프리뷰\r\n");
      out.write("        function readImage(input) {\r\n");
      out.write("            if(input.files && input.files[0]) {\r\n");
      out.write("                const reader = new FileReader()\r\n");
      out.write("                reader.onload = e => {\r\n");
      out.write("                    const previewImage = document.getElementById(\"preview_image\")\r\n");
      out.write("                    previewImage.src = e.target.result\r\n");
      out.write("                }\r\n");
      out.write("                reader.readAsDataURL(input.files[0])\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        const inputImage = document.getElementById(\"fname\")\r\n");
      out.write("        inputImage.addEventListener(\"change\", e => {\r\n");
      out.write("            readImage(e.target)\r\n");
      out.write("        })\r\n");
      out.write("    </script>\r\n");
      out.write("            \r\n");
      out.write("    <!-- footerarea -->\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("        <div id=\"title_introduce\">\r\n");
      out.write("            <h3 class=\"title\">[ Project 소개 ]</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"introduce_box\">\r\n");
      out.write("            <div class=\"introduce\">\r\n");
      out.write("            <h3 class=\"title\">Project Name</h3>\r\n");
      out.write("            <a id=\"project_story\">Golf Mate</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"introduce\">\r\n");
      out.write("            <h3 class=\"title\">Team Member</h3>\r\n");
      out.write("            <a id=\"project_member\">\r\n");
      out.write("                이재석\r\n");
      out.write("            </a>\r\n");
      out.write("            <a id=\"project_member\">\r\n");
      out.write("                이주희\r\n");
      out.write("            </a>\r\n");
      out.write("            <a id=\"project_member\">\r\n");
      out.write("                최수연\r\n");
      out.write("            </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	          ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	          ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /ACTIVITY/insert.jsp(25,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            <a href=\"login.do\">로그인</a>\r\n");
          out.write("	            <a href=\"member_join.do\">\r\n");
          out.write("	              회원가입\r\n");
          out.write("	            </a>\r\n");
          out.write("	            <style>#account {right : 0px;} #account a {padding: 0px 10px;}</style>\r\n");
          out.write("	          ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            <a href=\"mypage.do?member_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("	              <img src=\"CSS/icon/login.png\" alt=\"mypage\" name=\"mypage\" id=\"mypage\" title=\"마이페이지\">\r\n");
          out.write("	            </a>\r\n");
          out.write("	            <a href=\"logout.do\">\r\n");
          out.write("	              <img src=\"CSS/icon/logout.jpg\" alt=\"logout\" name=\"logout\" id=\"logout\" title=\"로그아웃\">\r\n");
          out.write("	            </a>\r\n");
          out.write("	            <br>\r\n");
          out.write("	            ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다.\r\n");
          out.write("	            <style>#account {position:absolute; text-align:right; right:0px; line-height: 20px;} #account a img {width: 25px; height: 30px; padding: 0px 13px;}</style>\r\n");
          out.write("	          ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /ACTIVITY/insert.jsp(87,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("entry");
      // /ACTIVITY/insert.jsp(87,32) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/ACTIVITY/insert.jsp(87,32) '${club}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${club}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /ACTIVITY/insert.jsp(146,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("entry");
      // /ACTIVITY/insert.jsp(146,40) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/ACTIVITY/insert.jsp(146,40) '${cc}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${cc}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                            <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.key}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${entry.value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
