/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-06 05:09:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.HTML;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1664934107135L));
    _jspx_dependants.put("jar:file:/C:/Users/JS/Desktop/project_1/Group4-Merge/golfzonTech_semi_project1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.9.0.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/footer.css\">\r\n");
      out.write("    <!-- join CSS -->\r\n");
      out.write("    <style>\r\n");
      out.write("        #container {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            width: 1130px;\r\n");
      out.write("            height: 1000px;\r\n");
      out.write("            padding: 0px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            background-color: rgba(176, 224, 230, 0.062);\r\n");
      out.write("        }\r\n");
      out.write("        #join_logo_img {\r\n");
      out.write("          width: 350px;\r\n");
      out.write("          height: 350px;\r\n");
      out.write("          background-repeat: no-repeat;\r\n");
      out.write("          position : relative;\r\n");
      out.write("          top: 30%;\r\n");
      out.write("          left: 8%;\r\n");
      out.write("        }\r\n");
      out.write("        #join_box {\r\n");
      out.write("          position : relative;\r\n");
      out.write("          background-color: rgba(135, 240, 125, 0.041);\r\n");
      out.write("          border: 1px solid rgb(32, 99, 26);\r\n");
      out.write("          margin: 0px;\r\n");
      out.write("          width : 500px;\r\n");
      out.write("          height: 700px;\r\n");
      out.write("          top : -20%;\r\n");
      out.write("          left : 50%;\r\n");
      out.write("        }\r\n");
      out.write("        #join_box_head {\r\n");
      out.write("          padding-left: 20px;\r\n");
      out.write("          font-size: 25px;\r\n");
      out.write("          position: relative;\r\n");
      out.write("          left: 29%;\r\n");
      out.write("          color : rgba(26, 138, 26, 0.753);\r\n");
      out.write("          letter-spacing : 7px;\r\n");
      out.write("        }\r\n");
      out.write("        .join_title {\r\n");
      out.write("          margin:0px;\r\n");
      out.write("          padding-bottom: 5px;\r\n");
      out.write("          font-size: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        #date {\r\n");
      out.write("          width: 200px;\r\n");
      out.write("        }\r\n");
      out.write("        #content ul li {\r\n");
      out.write("          float: left;\r\n");
      out.write("        }\r\n");
      out.write("        #content ul {\r\n");
      out.write("          display: inline-block;\r\n");
      out.write("          width: 480px;\r\n");
      out.write("        }\r\n");
      out.write("        #content h3 {\r\n");
      out.write("          font-size: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .input_text {\r\n");
      out.write("          width: 200px;\r\n");
      out.write("          height: 20px;\r\n");
      out.write("          margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        #idcheck {\r\n");
      out.write("          width: 75px;\r\n");
      out.write("          height: 25px;\r\n");
      out.write("          position: relative;\r\n");
      out.write("          left: 50%;\r\n");
      out.write("          transform: translateX(-50%);\r\n");
      out.write("          background: linear-gradient(125deg,#81eca5,#71e75c,#81ec95);\r\n");
      out.write("          background-position: left;\r\n");
      out.write("          background-size: 200%;\r\n");
      out.write("          color:white;\r\n");
      out.write("          font-weight: bold;\r\n");
      out.write("          border:none;\r\n");
      out.write("          cursor:pointer;\r\n");
      out.write("          transition: 0.4s;\r\n");
      out.write("          border-radius: 20px 20px 20px 20px;\r\n");
      out.write("        }\r\n");
      out.write("        #idcheck:hover {\r\n");
      out.write("          background-position: right;\r\n");
      out.write("        }\r\n");
      out.write("        #submit_btn {\r\n");
      out.write("          width: 300px;\r\n");
      out.write("          height:40px;\r\n");
      out.write("          position:relative;\r\n");
      out.write("          left:70%;\r\n");
      out.write("          transform: translateX(-50%);\r\n");
      out.write("          margin-bottom: 40px;\r\n");
      out.write("          background: linear-gradient(125deg,#81eca5,#71e75c,#81ec95);\r\n");
      out.write("          background-position: left;\r\n");
      out.write("          background-size: 200%;\r\n");
      out.write("          color:white;\r\n");
      out.write("          font-weight: bold;\r\n");
      out.write("          border:none;\r\n");
      out.write("          cursor:pointer;\r\n");
      out.write("          transition: 0.4s;\r\n");
      out.write("          display:inline;\r\n");
      out.write("          border-radius: 20px 20px 20px 20px;\r\n");
      out.write("        }\r\n");
      out.write("        #submit_btn:hover {\r\n");
      out.write("          background-position: right;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script>\r\n");
      out.write("    /* id 중복체크 */\r\n");
      out.write("    window.onload = function() {\r\n");
      out.write("        console.log(\"onload...\");\r\n");
      out.write("\r\n");
      out.write("        //2\r\n");
      out.write("        let btn_idCheck = document.querySelector(\"#btn_idCheck\");\r\n");
      out.write("        let result = document.querySelector(\"#result\");\r\n");
      out.write("        //3\r\n");
      out.write("        btn_idCheck.onclick = function(event) {\r\n");
      out.write("           console.log(\"onclick...\");\r\n");
      out.write("           let member_id = document.querySelector(\"#member_id\");\r\n");
      out.write("           // console.log(id);\r\n");
      out.write("           console.log(member_id.value);\r\n");
      out.write("\r\n");
      out.write("           let req = new XMLHttpRequest();\r\n");
      out.write("\r\n");
      out.write("           req.addEventListener(\"load\", function() {\r\n");
      out.write("              console.log(this.status);\r\n");
      out.write("              console.log(this.responseText);\r\n");
      out.write("              // {\"result\":\"Not OK\"}\r\n");
      out.write("              if (this.status == 200) {\r\n");
      out.write("                 try {\r\n");
      out.write("                    let txt_json = this.responseText;\r\n");
      out.write("                    let obj_json = JSON.parse(txt_json);\r\n");
      out.write("                    console.log(obj_json);\r\n");
      out.write("                    console.log(obj_json.result);\r\n");
      out.write("\r\n");
      out.write("                    let txt = \"\";\r\n");
      out.write("\r\n");
      out.write("                    if (obj_json.result == 'Not OK') {\r\n");
      out.write("                       txt = \"사용중인 아이디\";\r\n");
      out.write("                    } else {\r\n");
      out.write("                       txt = \"사용가능 아이디\";\r\n");
      out.write("                    }\r\n");
      out.write("                    result.innerHTML = txt;\r\n");
      out.write("                 } catch (e) {\r\n");
      out.write("                    console.log(\"json 형식이 아님.\");\r\n");
      out.write("                 }\r\n");
      out.write("              }//end if\r\n");
      out.write("           });\r\n");
      out.write("           req.open(\"GET\", \"http://localhost:8090/golfzonTech_semi_project1/idCheck.do?member_id=\" + member_id.value);\r\n");
      out.write("           req.send();\r\n");
      out.write("           event.preventDefault();\r\n");
      out.write("           event.stopPropagation();\r\n");
      out.write("        };\r\n");
      out.write("     };\r\n");
      out.write("    /* 공백체크 코드 */\r\n");
      out.write("      function checkValue() {\r\n");
      out.write("        var form = document.userInfo;\r\n");
      out.write("\r\n");
      out.write("        if(!form.member_id.value) {\r\n");
      out.write("          alert(\"아이디가 비어있습니다.\");\r\n");
      out.write("          return false;\r\n");
      out.write("        }\r\n");
      out.write("        /* if(form.idUncheck.value != \"idCheck\") {\r\n");
      out.write("          alert(\"아이디 중복체크를 해주세요.\");\r\n");
      out.write("          return false;\r\n");
      out.write("        } */\r\n");
      out.write("        if(!form.pw.value) {\r\n");
      out.write("          alert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("          return false;\r\n");
      out.write("        }\r\n");
      out.write("        if(!form.pwcheck.value) {\r\n");
      out.write("            alert(\"비밀번호를 확인해 주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("          }\r\n");
      out.write("        // 비밀번호와 비밀번호 확인이 동일한지 확인하는 코드\r\n");
      out.write("        if(form.pw.value != form.pwcheck.value) {\r\n");
      out.write("          alert(\"비밀번호가 다릅니다.\");\r\n");
      out.write("          return false;\r\n");
      out.write("        }\r\n");
      out.write("        if(!form.name.value) {\r\n");
      out.write("          alert(\"이름을 입력해주세요.\");\r\n");
      out.write("          return false;\r\n");
      out.write("        }\r\n");
      out.write("        if(!form.gender.value) {\r\n");
      out.write("            alert(\"성별를 선택해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("        if(form.location.value == \"지역\") {\r\n");
      out.write("        	console.log(form.location.value);\r\n");
      out.write("            alert(\"지역을 선택해주세요.\");\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- headarea -->\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("	    <div id=\"header_up\">\r\n");
      out.write("	      <div id=\"logo\">\r\n");
      out.write("	        <a href=\"home.do\">\r\n");
      out.write("	          <img id=\"logo_img\" src=\"CSS/logo/logo_small.png\" alt=\"logo_img\">\r\n");
      out.write("	        </a>\r\n");
      out.write("	      </div>\r\n");
      out.write("	      <div id=\"account\">\r\n");
      out.write("	        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	      </div>\r\n");
      out.write("	    </div>\r\n");
      out.write("	    <div id=\"header_nav\">\r\n");
      out.write("	      <ul id=\"nav_box\">\r\n");
      out.write("	        <li class=\"nav_item\">\r\n");
      out.write("	          <a href=\"club_selectAll.do\">모임</a>\r\n");
      out.write("	        </li>\r\n");
      out.write("	        <li class=\"nav_item\">\r\n");
      out.write("	          <a href=\"activity_selectAll.do\">액티비티</a>\r\n");
      out.write("	        </li>\r\n");
      out.write("	        <li class=\"nav_item\">\r\n");
      out.write("	          <a href=\"event_selectAll.do\">이벤트</a>\r\n");
      out.write("	        </li>\r\n");
      out.write("	      </ul>\r\n");
      out.write("	    </div>\r\n");
      out.write("  	</div>\r\n");
      out.write("\r\n");
      out.write("    <!-- main -->\r\n");
      out.write("    <div id=\"container\">\r\n");
      out.write("      <img id=\"join_logo_img\" src=\"CSS/logo/logo_large_nobackground.png\" alt=\"join_logo_img\">\r\n");
      out.write("      <div id=\"join_box\">\r\n");
      out.write("        <ul id=\"join_box_head\">\r\n");
      out.write("          <h2>회원가입</h2>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <div id=\"content\">\r\n");
      out.write("          <form method=\"post\" enctype=\"multipart/form-data\" class=\"from_design\" action=\"member_joinOK.do\" name=\"userInfo\" onsubmit=\"return checkValue()\">\r\n");
      out.write("            <ul>\r\n");
      out.write("              <h3 class=\"join_title\">아이디</h3>\r\n");
      out.write("              <li><input class=\"input_text\" type=\"text\" maxlength=\"25\" id=\"member_id\" name=\"member_id\" placeholder=\"아이디를 입력해 주세요.\"></li>\r\n");
      out.write("              <li><input type=\"button\" id=\"btn_idCheck\" name=\"btn_idCheck\" value=\"중복확인\"><span id=\"result\"></span></li>\r\n");
      out.write("              <li><input type=\"hidden\" name=\"idUncheck\" value=\"idUncheck\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <h3 class=\"join_title\">비밀번호</h3>\r\n");
      out.write("              <li><input class=\"input_text\" type=\"password\" name=\"pw\" placeholder=\"비밀번호를 입력해 주세요.\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <h3 class=\"join_title\">비밀번호 확인</h3>\r\n");
      out.write("              <li><input class=\"input_text\" type=\"password\" name=\"pwcheck\" placeholder=\"비밀번호를 확인해 주세요.\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <h3 class=\"join_title\">프로필</h3>\r\n");
      out.write("              <li><input type=\"file\" name=\"upfile\" value=\"upfile\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <h3 class=\"join_title\">이름</h3>\r\n");
      out.write("              <li><input class=\"input_text\" type=\"text\" name=\"name\" placeholder=\"이름을 입력해 주세요.\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <h3 class=\"join_title\">생년월일</h3>\r\n");
      out.write("              <li><input type=\"date\" name=\"birthday\" id=\"birthday\" class=\"birthday\" title=\"생년월일\" value=\"1970-01-01\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <h3 class=\"join_title\">성별</h3>\r\n");
      out.write("              <li><input type=\"radio\" name=\"gender\" value=\"남\">남</li>\r\n");
      out.write("              <li><input type=\"radio\" name=\"gender\" value=\"여\">여</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <h3 class=\"join_title\">지역</h3>\r\n");
      out.write("              <li>\r\n");
      out.write("				<select name=\"location\" id=\"location\">\r\n");
      out.write("					<option selected hidden>지역</option>\r\n");
      out.write("                    <option value=\"서울\">서울</option>\r\n");
      out.write("                    <option value=\"경기\">경기</option>\r\n");
      out.write("                    <option value=\"강원\">강원</option>\r\n");
      out.write("                    <option value=\"전북\">전북</option>\r\n");
      out.write("                    <option value=\"전남\">전남</option>\r\n");
      out.write("                    <option value=\"경북\">경북</option>\r\n");
      out.write("                    <option value=\"경남\">경남</option>\r\n");
      out.write("                    <option value=\"충북\">충북</option>\r\n");
      out.write("                    <option value=\"충남\">충남</option>\r\n");
      out.write("                    <option value=\"제주\">제주</option>\r\n");
      out.write("                    <option value=\"대전\">대전</option>\r\n");
      out.write("                    <option value=\"인천\">인천</option>\r\n");
      out.write("                    <option value=\"광주\">광주</option>\r\n");
      out.write("                    <option value=\"대구\">대구</option>\r\n");
      out.write("                    <option value=\"부신\">부산</option>\r\n");
      out.write("                </select>\r\n");
      out.write("			  </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("              <li><input id=\"submit_btn\" type=\"submit\" name=\"join\" value=\"가입\"></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   	<!-- footerarea -->\r\n");
      out.write("    <div id=\"footer\">\r\n");
      out.write("      <div id=\"title_introduce\">\r\n");
      out.write("        <h3 class=\"title\">[ Project 소개 ]</h3>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"introduce_box\">\r\n");
      out.write("        <div class=\"introduce\">\r\n");
      out.write("          <h3 class=\"title\">Project Name</h3>\r\n");
      out.write("          <a id=\"project_story\">Golf Mate</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"introduce\">\r\n");
      out.write("          <h3 class=\"title\">Team Member</h3>\r\n");
      out.write("          <a id=\"project_member\">\r\n");
      out.write("            이재석\r\n");
      out.write("          </a>\r\n");
      out.write("          <a id=\"project_member\">\r\n");
      out.write("            이주희\r\n");
      out.write("          </a>\r\n");
      out.write("          <a id=\"project_member\">\r\n");
      out.write("            최수연\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	          ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	          ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("	        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /HTML/join.jsp(212,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            <a href=\"login.do\">로그인</a>\r\n");
          out.write("	            <a href=\"member_join.do\">\r\n");
          out.write("	              회원가입\r\n");
          out.write("	            </a>\r\n");
          out.write("	            <style>#account {right : 0px;} #account a {padding: 0px 10px;}</style>\r\n");
          out.write("	          ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	            ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다.\r\n");
          out.write("	            <a href=\"mypage.do?member_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("	              <img src=\"CSS/icon/login.png\" alt=\"mypage\" name=\"mypage\" id=\"mypage\" title=\"마이페이지\">\r\n");
          out.write("	            </a>\r\n");
          out.write("	            <a href=\"logout.do\">\r\n");
          out.write("	              <img src=\"CSS/icon/logout.jpg\" alt=\"logout\" name=\"logout\" id=\"logout\" title=\"로그아웃\">\r\n");
          out.write("	            </a>\r\n");
          out.write("	            <style>#account {position:absolute; top:20px; left:900px; width:230px} #account a img {width: 25px; height: 30px; padding: 0px 10px;}</style>\r\n");
          out.write("	          ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
