/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-05 05:23:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ALBUM;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class selectAll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1664934107135L));
    _jspx_dependants.put("jar:file:/C:/Users/JS/Desktop/project_1/Group4-Merge/golfzonTech_semi_project1/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>모임_앨범</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/header.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/footer.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"CSS/album/selectAll.css\">\r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("   <!-- headarea -->\r\n");
      out.write("    <div id=\"header\">\r\n");
      out.write("       <div id=\"header_up\">\r\n");
      out.write("         <div id=\"logo\">\r\n");
      out.write("           <a href=\"home.do\">\r\n");
      out.write("             <img id=\"logo_img\" src=\"CSS/logo/logo_small.png\" alt=\"logo_img\">\r\n");
      out.write("           </a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div id=\"account\">\r\n");
      out.write("           ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div id=\"header_nav\">\r\n");
      out.write("         <ul id=\"nav_box\">\r\n");
      out.write("           <li class=\"nav_item\">\r\n");
      out.write("             <a href=\"club_selectAll.do\">모임</a>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"nav_item\">\r\n");
      out.write("             <a href=\"activity_selectAll.do\">액티비티</a>\r\n");
      out.write("           </li>\r\n");
      out.write("           <li class=\"nav_item\">\r\n");
      out.write("             <a href=\"event_selectAll.do\">이벤트</a>\r\n");
      out.write("           </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("       </div>\r\n");
      out.write("     </div>\r\n");
      out.write("    \r\n");
      out.write("    <!-- main -->\r\n");
      out.write("  <div id=\"container\">\r\n");
      out.write("    <div id=\"club_name_box\">\r\n");
      out.write("      <div id=\"club_title\">\r\n");
      out.write("        <p style=\"font-size: 30px; padding-left: 30px;\">\r\n");
      out.write("            <strong>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</strong>\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- 게시판 버튼영역 -->\r\n");
      out.write("    <div id=\"club_content\">\r\n");
      out.write("      <ul>\r\n");
      out.write("        <li><a href=\"board_selectAll.do?club_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&club_name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">게시글</a></li>\r\n");
      out.write("        <li><a href=\"club_activity.do?club_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&club_name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">액티비티</a></li>\r\n");
      out.write("        <li><a href=\"album_selectAll.do?club_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&club_name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"color:blue;\">앨범</a></li>\r\n");
      out.write("        <li><a href=\"vote_selectAll.do?club_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&club_name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">투표</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"board_content_box\">\r\n");
      out.write("      <div id=\"board_sort_box\">\r\n");
      out.write("        <ul style=\"padding-left: 20px;\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <form action=\"album_searchList.do?club_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" method=\"get\">\r\n");
      out.write("              <select name=\"searchKey\" id=\"searchKey\" style=\"height: 30px; font-size: 15px; border-radius: 5px; border: 2px solid gray;\">\r\n");
      out.write("                <option value=\"title\">title</option>\r\n");
      out.write("                <option value= \"writer\">writer</option>\r\n");
      out.write("              </select> \r\n");
      out.write("              <input type=\"text\" name=\"searchWord\" id=\"searchWord\" value=\"title\" style=\"width: 300px; height: 30px; font-size: 15px; border-radius: 5px; border: 2px solid gray;\">\r\n");
      out.write("              <input type=\"hidden\" name=\"club_id\" id=\"club_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("              <input type=\"submit\" style=\"height: 30px; font-size: 15px; border-radius: 5px; border: 2px solid gray;\">\r\n");
      out.write("            </form>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul style=\"position: absolute; top: 7%; left: 86%;\">\r\n");
      out.write("          <li><a style=\"font-size: 18px;\" onclick=\"action('insert')\">앨범등록</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul id=\"sort_list\" style=\"padding-left: 20px; font-size:15px; margin: 30px 0px 0px 0px;\">\r\n");
      out.write("          <li>작성일기준 |</li>\r\n");
      out.write("          <li><a href=\"album_selectAll.do?club_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&club_name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&order=desc\">내림차순</a></li>\r\n");
      out.write("          <li><a href=\"album_selectAll.do?club_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&club_name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&order=asc\">오름차순</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div style=\"width: 1130px;\" id=\"board_content_ul\">\r\n");
      out.write("        <!-- selectAll -->\r\n");
      out.write("        <!-- 앨범 정렬 -->\r\n");
      out.write("        <div id=\"album_box\">\r\n");
      out.write("          <!-- c문 출력 -->\r\n");
      out.write("           ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("          <!-- c문 출력 여기까지-->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- insert 앨범등록 버튼을 통해서 반응형으로 생성 -->\r\n");
      out.write("      <div id=\"album_insert\" style=\"display: none;\">\r\n");
      out.write("        <form action=\"album_insertOK.do?\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("          <!-- 제목 -->\r\n");
      out.write("          <input type=\"text\" placeholder=\"앨범의 제목을 작성해 주세요.\" id=\"album_title\" name=\"album_title\" maxlength=\"25\">\r\n");
      out.write("          <!-- user의 id 가져오기 -->\r\n");
      out.write("          <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"insert_writer\" name=\"insert_writer\">\r\n");
      out.write("          <br>\r\n");
      out.write("          <ul style=\"padding: 0px; margin: 0px;\">\r\n");
      out.write("            <!-- 파일 업로드 공간 -->\r\n");
      out.write("            <li><img id=\"preview_image\" src=\"\"></li>\r\n");
      out.write("            <li><input type=\"file\" id=\"upFile\" name=\"upFile\" multiple></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <!-- 제출, 취소 버튼 -->\r\n");
      out.write("          <label class=\"submit\" for=\"insert_submit\" style=\"right:90px\"><a>등 록</a></label>\r\n");
      out.write("          <input type=\"submit\" id=\"insert_submit\" hidden>\r\n");
      out.write("          <label class=\"submit\" for=\"insert_cancle\" style=\"right:35px\" onclick=\"action('cancle_insert')\"><a>취 소</a></label>\r\n");
      out.write("          <input type=\"button\" id=\"insert_cancle\" hidden>\r\n");
      out.write("          <input type=\"text\" name=\"club_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("          <input type=\"text\" name=\"club_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- selectOne 앨범선택으로 자동으로 값을 가져와서 출력 -->\r\n");
      out.write("      <div id=\"selectOne\" style=\"display: none;\">\r\n");
      out.write("        <form action=\"album_updateOK.do\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("          <!-- 제목 자동으로 가져온다. -->\r\n");
      out.write("          <input type=\"text\" id=\"selectOne_title\" name=\"selectOne_title\" value=\"\">\r\n");
      out.write("          <!-- user의 id 가져오기 -->\r\n");
      out.write("          <input type=\"text\" id=\"selectOne_writer\" name=\"selectOne_writer\" value=\"\" readonly>\r\n");
      out.write("          <!-- 작성일 -->\r\n");
      out.write("          <input type=\"text\" value=\"\" id=\"update_date\" name=\"update_date\" readonly>\r\n");
      out.write("          <!-- 앨범ID -->\r\n");
      out.write("          <input type=\"hidden\" value=\"\" id=\"update_id\" name=\"update_id\" readonly>\r\n");
      out.write("          <br>\r\n");
      out.write("          <ul style=\"padding: 0px; margin: 0px;\">\r\n");
      out.write("            <!-- 수정 파일 업로드 공간 -->\r\n");
      out.write("            <li><img id=\"update_image\" src=\"\"></li>\r\n");
      out.write("            <li><input type=\"file\" id=\"updateFile\" name=\"updateFile\" multiple></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("          <!-- 수정, 삭제버튼 -->\r\n");
      out.write("          <label class=\"submit writer_power\" for=\"update_submit\" style=\"right: 145px;\"><a>수 정</a></label>\r\n");
      out.write("          <input type=\"submit\" id=\"update_submit\" hidden>\r\n");
      out.write("          \r\n");
      out.write("          <label class=\"submit writer_power\" for=\"album_delete_button\" style=\"right: 90px;\"><a id=\"delete_button\" href=\"\">삭 제</a></label>\r\n");
      out.write("          <input type=\"submit\" id=\"album_delete_button\" hidden>\r\n");
      out.write("          \r\n");
      out.write("          <label class=\"submit\" for=\"update_cancle\" style=\"right:35px\" onclick=\"action('cancle_insert')\"><a>닫 기</a></label>\r\n");
      out.write("          <input type=\"button\" id=\"update_cancle\" hidden>\r\n");
      out.write("          \r\n");
      out.write("          <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"club_id\" hidden>\r\n");
      out.write("          <input type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" name=\"club_name\" hidden>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script>\r\n");
      out.write("    // selectOne 자료 가져오기\r\n");
      out.write("    // insert 앨범 사진 미리보기 및 이름 출력\r\n");
      out.write("    function readImage(input) {\r\n");
      out.write("        if(input.files && input.files[0]) {\r\n");
      out.write("            const reader = new FileReader()\r\n");
      out.write("            reader.onload = e => {\r\n");
      out.write("                const previewImage = document.getElementById(\"preview_image\")\r\n");
      out.write("                previewImage.src = e.target.result\r\n");
      out.write("            }\r\n");
      out.write("            reader.readAsDataURL(input.files[0])\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    const inputImage = document.getElementById(\"upFile\")\r\n");
      out.write("    inputImage.addEventListener(\"change\", e => {\r\n");
      out.write("        readImage(e.target)\r\n");
      out.write("    })\r\n");
      out.write("    // insert, selectOne, updateOk, delete 출력\r\n");
      out.write("    function action(x,y,z){\r\n");
      out.write("      document.getElementById('album_insert').setAttribute('style','display:none');\r\n");
      out.write("      document.getElementById('selectOne').setAttribute('style','display:none');\r\n");
      out.write("      if(x == \"insert\") {\r\n");
      out.write("        document.getElementById('album_insert').setAttribute('style','display:block');\r\n");
      out.write("      } else if(x == \"update\") {\r\n");
      out.write("          location.href = \"album_updateOK.do\";\r\n");
      out.write("       } else if(x == \"delete\") {\r\n");
      out.write("          var msg = confirm(\"정말 삭제하시겠습니까?\");\r\n");
      out.write("          let album_id = y;\r\n");
      out.write("   		  let club_id = z;\r\n");
      out.write("          if(msg==true){\r\n");
      out.write("             alert(\"게시글을 삭제하였습니다.\");\r\n");
      out.write("          } else {\r\n");
      out.write("             return false;\r\n");
      out.write("          }\r\n");
      out.write("      }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("	// session 값 가져와서 작성자와 맞는지 확인\r\n");
      out.write("	");
String session_id = (String)session.getAttribute("member_id");
      out.write("\r\n");
      out.write("	let session = \"");
      out.print(session_id);
      out.write("\";\r\n");
      out.write("	console.log(\"session : \"+session);\r\n");
      out.write("    \r\n");
      out.write("    function selectOne(x) {\r\n");
      out.write("    	if(x == x) {\r\n");
      out.write("            document.getElementById('selectOne').setAttribute('style','display:block');\r\n");
      out.write("            let update_id = document.getElementById(x+'_id').outerText;\r\n");
      out.write("            let club_id = document.getElementById('club_id').value;\r\n");
      out.write("            console.log(\"club_id : \"+club_id);\r\n");
      out.write("            // selectOne에 선택한 객체의 값 넣기\r\n");
      out.write("            console.log(document.getElementById(x+'_text').outerText)\r\n");
      out.write("            console.log(document.getElementById(x+'_writer').outerText)\r\n");
      out.write("            console.log(document.getElementById(x+'_date').outerText)\r\n");
      out.write("            console.log(document.getElementById(x+'_id').outerText)\r\n");
      out.write("            console.log(document.getElementById(x+'_fname').getAttribute('src'))\r\n");
      out.write("            document.getElementById('selectOne_title').setAttribute('value',document.getElementById(x+'_text').outerText);\r\n");
      out.write("            document.getElementById('selectOne_writer').setAttribute('value',document.getElementById(x+'_writer').outerText);\r\n");
      out.write("            document.getElementById('update_date').setAttribute('value',document.getElementById(x+'_date').outerText);\r\n");
      out.write("            document.getElementById('update_id').setAttribute('value',document.getElementById(x+'_id').outerText);\r\n");
      out.write("            document.getElementById('delete_button').setAttribute('href',\"album_deleteOK.do?album_id=\"+x+\"&club_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&club_name=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.club_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\");\r\n");
      out.write("            document.getElementById('update_image').setAttribute('src',document.getElementById(x+'_fname').getAttribute('src'));\r\n");
      out.write("            \r\n");
      out.write("            let comment_writer = document.getElementById('selectOne_writer').value;\r\n");
      out.write("      	  	console.log(\"comment_writer : \"+comment_writer)\r\n");
      out.write("      	  	console.log(session == comment_writer)\r\n");
      out.write("			let writer_power = document.getElementsByClassName('writer_power');      	  	\r\n");
      out.write("      	  	if(session == comment_writer) {\r\n");
      out.write("      	  		console.log(\"작성자\")\r\n");
      out.write("      		 	for (var i = 0; i < writer_power.length; i++) {\r\n");
      out.write("      		 		writer_power[i].addAttribute('style','display:block');\r\n");
      out.write("	      		}\r\n");
      out.write("      	  	} else {\r\n");
      out.write("	      	  	console.log(\"작성자가 아님\")\r\n");
      out.write("	  		 	for (var i = 0; i < writer_power.length; i++) {\r\n");
      out.write("	  		 		writer_power[i].setAttribute('style','display:none');\r\n");
      out.write("	      		}\r\n");
      out.write("      	  	}\r\n");
      out.write("    	} \r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    // 작성일 출력 함수\r\n");
      out.write("    let date = new Date();\r\n");
      out.write("    let year = date.getFullYear();\r\n");
      out.write("    let month = date.getMonth() + 1;\r\n");
      out.write("    let day = date.getDate();\r\n");
      out.write("    let hour = date.getHours();\r\n");
      out.write("    let minute = date.getMinutes();\r\n");
      out.write("    wdate = year+\"-\"+month+\"-\"+day+\" \"+hour+\":\"+minute;\r\n");
      out.write("    console.log(wdate)\r\n");
      out.write("    document.getElementById(\"update_date\").setAttribute('value',wdate);\r\n");
      out.write("  </script>\r\n");
      out.write("  \r\n");
      out.write("  <!-- footerarea -->\r\n");
      out.write("  <div id=\"footer\">\r\n");
      out.write("    <div id=\"title_introduce\">\r\n");
      out.write("      <h3 class=\"title\">[ Project 소개 ]</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"introduce_box\">\r\n");
      out.write("      <div class=\"introduce\">\r\n");
      out.write("        <h3 class=\"title\">Project Name</h3>\r\n");
      out.write("        <a id=\"project_story\">Golf Mate</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"introduce\">\r\n");
      out.write("        <h3 class=\"title\">Team Member</h3>\r\n");
      out.write("        <a id=\"project_member\">\r\n");
      out.write("          이재석\r\n");
      out.write("        </a>\r\n");
      out.write("        <a id=\"project_member\">\r\n");
      out.write("          이주희\r\n");
      out.write("        </a>\r\n");
      out.write("        <a id=\"project_member\">\r\n");
      out.write("          최수연\r\n");
      out.write("        </a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("             ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("             ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("           ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /ALBUM/selectAll.jsp(26,13) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("               <a href=\"login.do\">로그인</a>\r\n");
          out.write("               <a href=\"member_join.do\">\r\n");
          out.write("                 회원가입\r\n");
          out.write("               </a>\r\n");
          out.write("               <style>#account {right : 0px;} #account a {padding: 0px 10px;}</style>\r\n");
          out.write("             ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("               <a href=\"mypage.do?member_id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                 <img src=\"CSS/icon/login.png\" alt=\"mypage\" name=\"mypage\" id=\"mypage\" title=\"마이페이지\">\r\n");
          out.write("               </a>\r\n");
          out.write("               <a href=\"logout.do\">\r\n");
          out.write("                 <img src=\"CSS/icon/logout.jpg\" alt=\"logout\" name=\"logout\" id=\"logout\" title=\"로그아웃\">\r\n");
          out.write("               </a>\r\n");
          out.write("               <br>\r\n");
          out.write("               ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다.\r\n");
          out.write("               <style>#account {position:absolute; text-align:right; right:0px; line-height: 20px;} #account a img {width: 25px; height: 30px; padding: 0px 13px;}</style>\r\n");
          out.write("             ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /ALBUM/selectAll.jsp(110,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("album");
      // /ALBUM/selectAll.jsp(110,11) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/ALBUM/selectAll.jsp(110,11) '${album_list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${album_list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("	          <ul class=\"album_item\">\r\n");
            out.write("	            <a id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.album_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" onclick=\"selectOne(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.album_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(")\">\r\n");
            out.write("	            <li><img src=\"upload/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.fname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"album_img\" class=\"album_img\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.album_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("_fname\"></li>\r\n");
            out.write("	            <li id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.album_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("_text\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("	            <li id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.album_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("_writer\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("	            <li id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.album_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("_date\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.wdate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("	            <li id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.album_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("_id\" style=\"display:none;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.album_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</li>\r\n");
            out.write("	            </a>\r\n");
            out.write("	          </ul>\r\n");
            out.write("          ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
